### ISSUE TITLE
Dysco error when attempting to read MS

### ISSUE THREAD

**Issue by mknapp55** [kernsuite/packaging#196]
I get the error below when attempting to run a simple script that accesses a dysco compressed MS.  I've used only Kern to install relevant packages (casacore, python-casacore, dysco).  Is there a special installation order to get casacore/pyrap to work with dysco compressed files?  I originally posted this issue to the dysco repo, but was advised to post it here instead.

```    ms = pt.table(msname, ack=False)
  File "/usr/lib/python2.7/dist-packages/casacore/tables/table.py", line 375, in __init__
    Table.__init__(self, tabname, lockopt, opt)
RuntimeError: Table DataManager error: Data Manager class DyscoStMan is not registered
  Check (DY)LD_LIBRARY_PATH matches the libraries used during the build of DyscoStMan```

**Comment by gijzelaerr** [comment]
can you give me the simple script please.

**Comment by mknapp55** [comment]
https://github.com/lofar-astron/LOFAR-Contributions/blob/master/Maintained/plot_Ateam_elevation.py

**Comment by gijzelaerr** [comment]
can you supply the dysco compressed MS?

**Comment by gijzelaerr** [comment]
or give me small dysco compressed ms :)

**Comment by mknapp55** [comment]
I can't get basic access the the MS via casa (see below).  I usually split large MSs via split() in casa - if there's another way to break out a small piece, let me know.

```
CASA <7>: listobs('L693114_SB079_uv.MS')
2019-04-02 15:29:49     SEVERE  listobs::ms::open       Exception Reported: Table DataManager error: Data Manager class DyscoStMan is not registered
2019-04-02 15:29:49     SEVERE  listobs::::     *** Error *** Table DataManager error: Data Manager class DyscoStMan is not registered
2019-04-02 15:29:49     SEVERE  ms::detached    ms is not attached to a file - cannot perform operation.
2019-04-02 15:29:49     SEVERE  ms::detached+   Call ms.open('filename') to reattach.
  Out[7]: False
```

I tried ms.open() and got the same error:
```
CASA <11>: ms.open('L693114_SB000_uv.MS')
2019-04-02 15:35:05     SEVERE  ms::open        Exception Reported: Table DataManager error: Data Manager class DyscoStMan is not registered
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)

/home/mknapp/casa-release-4.6.0-el6/lib/python2.7/casapy.py in <module>()
----> 1
      2
      3
      4
      5

/home/mknapp/casa-release-4.6.0-el6/lib/python2.7/__casac__/ms.pyc in open(self, *args, **kwargs)
    405
    406         """
--> 407         return _ms.ms_open(self, *args, **kwargs)
    408
    409     def reset(self):

RuntimeError: Table DataManager error: Data Manager class DyscoStMan is not registered
```

**Comment by gijzelaerr** [comment]
i can't reproduce the error without a sample dysco compressed ms.

**Comment by mknapp55** [comment]
Here's a [link](https://www.dropbox.com/s/fahbm6trt8kio9p/L693114_SB000_uv.MS.tar?dl=0) to download one of the MSs.  It's 2.4G, but I can't cut it down because I can't manipulate it in CASA.

**Comment by gijzelaerr** [comment]
i'll have a look when i find the time.

**Comment by gijzelaerr** [comment]
I can confirm this issue, looks like the dysco in KERN-5 is built against casacore < 3.0. Making a new package now which should solve the issue.

**Comment by gijzelaerr** [comment]
i've pushed a new dysco package, does this package solve your issues?

**Comment by mknapp55** [comment]
I used apt-get update to update dysco and casacore-dev, but still get the same error.  Which versions should I have of those two packages?  Are there other packages I need to upgrade?  Or should I remove and reinstall the packages?

**Comment by gijzelaerr** [comment]
did you only run `update`? because that doesn't update the package, only the cache. I didn't push a new version of `casacore-dev`. What version of Dysco do you have now? It should be `1.2-1kern1`

**Comment by mknapp55** [comment]
I removed and reinstalled dysco.  It is `1.2-1kern1`.  I still get the same error.
``` 
sudo apt remove --purge dysco
sudo apt autoremove
sudo apt-get install dysco
```

**Comment by gijzelaerr** [comment]
bingo! This is actually an issue with the `python-casacore` package, which is still linked against casacore 2.  Working on a fix.

**Comment by gijzelaerr** [comment]
this should be fixed in KERN-5 and KERN-dev now. Please update python-casacore to `3.0.0-1kern1` and dysco to `1.2.1kern1`. Note that the dysco library/dev packages have been renamed. Please reopen this issue if this doesn't solve your issue.
